In [1]:
import numpy as np

In [9]:
# Player IDs (10 players)
players = np.arange(1, 11)
#random points scored in 5 games (10 players × 5 games)
points = np.random.randint(0, 30, size=(10,5))

In [11]:
print("Players:", players)
print("Points:\n", points)
print("Shape : ", points.shape, "Size : ", points.size, "Dtype:", points.dtype)

Players: [ 1  2  3  4  5  6  7  8  9 10]
Points:
 [[ 4  9 24 10  9]
 [ 8  1 16  4 26]
 [26 17 18 17 19]
 [ 8 27 21 28 26]
 [23  2  6 11  4]
 [ 5  8 24 28  7]
 [21 14 22  5  5]
 [19 29 23  8 17]
 [15  4 22 13 27]
 [24  7 25 17  3]]
Shape :  (10, 5) Size :  50 Dtype: int32


In [12]:
print("Points of player 1:", points[0])
print("Points in game 3 (all players):", points[:, 2])
print("Points of players 1–3 in games 2–4:\n", points[0:3, 1:4])

Points of player 1: [ 4  9 24 10  9]
Points in game 3 (all players): [24 16 18 21  6 24 22 23 22 25]
Points of players 1–3 in games 2–4:
 [[ 9 24 10]
 [ 1 16  4]
 [17 18 17]]


In [ ]:
## Broadcasting
bonus = 2
points_bonus = points + bonus
points_bonus

array([[ 6, 11, 26, 12, 11],
       [10,  3, 18,  6, 28],
       [28, 19, 20, 19, 21],
       [10, 29, 23, 30, 28],
       [25,  4,  8, 13,  6],
       [ 7, 10, 26, 30,  9],
       [23, 16, 24,  7,  7],
       [21, 31, 25, 10, 19],
       [17,  6, 24, 15, 29],
       [26,  9, 27, 19,  5]], dtype=int32)

In [15]:
## Vectorized Operation

weights = np.array([1, 1.2, 1, 1.5, 1])
weighted_points = points*weights
weighted_points

array([[ 4. , 10.8, 24. , 15. ,  9. ],
       [ 8. ,  1.2, 16. ,  6. , 26. ],
       [26. , 20.4, 18. , 25.5, 19. ],
       [ 8. , 32.4, 21. , 42. , 26. ],
       [23. ,  2.4,  6. , 16.5,  4. ],
       [ 5. ,  9.6, 24. , 42. ,  7. ],
       [21. , 16.8, 22. ,  7.5,  5. ],
       [19. , 34.8, 23. , 12. , 17. ],
       [15. ,  4.8, 22. , 19.5, 27. ],
       [24. ,  8.4, 25. , 25.5,  3. ]])

In [17]:
## Aggregation - 

print("Total points by each player:", points.sum(axis=1))
print("Average points per game:", points.mean(axis=0))
print("Overall max score:", points.max())

Total points by each player: [ 56  55  97 110  46  72  67  96  81  76]
Average points per game: [15.3 11.8 20.1 14.1 14.3]
Overall max score: 29


In [19]:
## Boolean masking and filtering
print("Players who scored > 100 total : ", players[points.sum(axis=1)>100])
print("Game 1 scores > 20 : ", points[points[:, 0]>20, 0])

Players who scored > 100 total :  [4]
Game 1 scores > 20 :  [26 23 21 24]


In [25]:
## Reshaping and stacking - 
flat = points.flatten()
print("Flattened : ", flat[:15])

# reshaped = points.reshape(5, 10)
# reshaped

points_team2 = np.random.randint(0, 30, size=(10,5))
combined = np.vstack([points, points_team2])
print("Combined shape : ", combined.shape)
combined

Flattened :  [ 4  9 24 10  9  8  1 16  4 26 26 17 18 17 19]
Combined shape :  (20, 5)


array([[ 4,  9, 24, 10,  9],
       [ 8,  1, 16,  4, 26],
       [26, 17, 18, 17, 19],
       [ 8, 27, 21, 28, 26],
       [23,  2,  6, 11,  4],
       [ 5,  8, 24, 28,  7],
       [21, 14, 22,  5,  5],
       [19, 29, 23,  8, 17],
       [15,  4, 22, 13, 27],
       [24,  7, 25, 17,  3],
       [ 7, 29, 28, 19,  2],
       [21,  9, 21, 26, 11],
       [24, 25, 16, 15, 19],
       [13,  1, 11, 13, 17],
       [25, 10, 12,  0, 13],
       [ 8, 20,  8, 20, 21],
       [29, 19, 20,  9, 21],
       [21,  3, 18, 16,  0],
       [29,  7, 23, 29, 20],
       [28,  1, 15, 23,  7]], dtype=int32)

In [28]:
## Liner algebra - 

corr = np.corrcoef(points)
print("Corelation shape : ", corr.shape)
corr

Corelation shape :  (10, 10)


array([[ 1.        ,  0.27285159, -0.49517597,  0.24469947, -0.45487414,
         0.63261496,  0.33183193,  0.20026086,  0.3382317 ,  0.35111875],
       [ 0.27285159,  1.        ,  0.05236751,  0.01495425, -0.22374009,
        -0.15214904, -0.15874697, -0.10528236,  0.95198282, -0.22731368],
       [-0.49517597,  0.05236751,  1.        , -0.95054715,  0.86959575,
        -0.55288356,  0.48156856, -0.02044961,  0.12450006,  0.43097171],
       [ 0.24469947,  0.01495425, -0.95054715,  1.        , -0.84780704,
         0.39945551, -0.71637503, -0.10900703, -0.08909587, -0.64621173],
       [-0.45487414, -0.22374009,  0.86959575, -0.84780704,  1.        ,
        -0.14232421,  0.36552211, -0.36097985, -0.03103185,  0.64747946],
       [ 0.63261496, -0.15214904, -0.55288356,  0.39945551, -0.14232421,
         1.        , -0.12620978, -0.4813173 ,  0.0570517 ,  0.41961506],
       [ 0.33183193, -0.15874697,  0.48156856, -0.71637503,  0.36552211,
        -0.12620978,  1.        ,  0.58326109

In [29]:
## Dot product - 
print("Player 1 weighted : ", np.dot(points[0], weights))

Player 1 weighted :  62.8


In [32]:
## Random and reproducibility - 

np.random.seed(42)
random_scores = np.random.normal(loc=15, scale=5, size=(10,5))
random_scores

array([[17.48357077, 14.30867849, 18.23844269, 22.61514928, 13.82923313],
       [13.82931522, 22.89606408, 18.83717365, 12.65262807, 17.71280022],
       [12.68291154, 12.67135123, 16.20981136,  5.43359878,  6.37541084],
       [12.18856235,  9.9358444 , 16.57123666, 10.45987962,  7.93848149],
       [22.32824384, 13.8711185 , 15.33764102,  7.87625907, 12.27808638],
       [15.55461295,  9.24503211, 16.87849009, 11.99680655, 13.54153125],
       [11.99146694, 24.26139092, 14.93251388,  9.71144536, 19.11272456],
       [ 8.89578175, 16.04431798,  5.20164938,  8.35906976, 15.98430618],
       [18.6923329 , 15.85684141, 14.42175859, 13.49448152,  7.60739005],
       [11.40077896, 12.69680615, 20.28561113, 16.71809145,  6.18479922]])