### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
import tensorflow as tf
print(tf.__version__)

ImportError: DLL load failed while importing _pywrap_toco_api: The specified procedure could not be found.

In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[275, 299, 177, 361], [275, 299, 177, 364], [275, 320, 177, 308], [346, 134, 428, 378, 39], [346, 134, 428, 378, 214], [12, 275, 383, 177, 294], [499, 252, 455, 378]]


### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 275 299 177 361]
 [  0   0   0   0 275 299 177 364]
 [  0   0   0   0 275 320 177 308]
 [  0   0   0 346 134 428 378  39]
 [  0   0   0 346 134 428 378 214]
 [  0   0   0  12 275 383 177 294]
 [  0   0   0   0 499 252 455 378]]


In [13]:
## 10 feature dimesnions
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 275, 299, 177, 361])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 318ms/step


array([[-0.00480906,  0.00471622, -0.04356424, -0.0140356 , -0.00133337,
        -0.01865225,  0.03476957,  0.01611543, -0.0014398 , -0.02882995],
       [-0.00480906,  0.00471622, -0.04356424, -0.0140356 , -0.00133337,
        -0.01865225,  0.03476957,  0.01611543, -0.0014398 , -0.02882995],
       [-0.00480906,  0.00471622, -0.04356424, -0.0140356 , -0.00133337,
        -0.01865225,  0.03476957,  0.01611543, -0.0014398 , -0.02882995],
       [-0.00480906,  0.00471622, -0.04356424, -0.0140356 , -0.00133337,
        -0.01865225,  0.03476957,  0.01611543, -0.0014398 , -0.02882995],
       [ 0.01147298, -0.01466576, -0.00783487, -0.02551963, -0.02508037,
        -0.0115932 , -0.02833921, -0.04328271, -0.04807395,  0.02363879],
       [-0.02156421, -0.01743867,  0.0058993 , -0.03681654,  0.02154856,
         0.00935637, -0.01652386, -0.02215796,  0.03750986, -0.03689753],
       [ 0.04422344, -0.02944503, -0.02354667,  0.0357141 , -0.04980476,
        -0.03795732,  0.00607185, -0.01719254

In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 49ms/step
[[[-0.00480906  0.00471622 -0.04356424 -0.0140356  -0.00133337
   -0.01865225  0.03476957  0.01611543 -0.0014398  -0.02882995]
  [-0.00480906  0.00471622 -0.04356424 -0.0140356  -0.00133337
   -0.01865225  0.03476957  0.01611543 -0.0014398  -0.02882995]
  [-0.00480906  0.00471622 -0.04356424 -0.0140356  -0.00133337
   -0.01865225  0.03476957  0.01611543 -0.0014398  -0.02882995]
  [-0.00480906  0.00471622 -0.04356424 -0.0140356  -0.00133337
   -0.01865225  0.03476957  0.01611543 -0.0014398  -0.02882995]
  [ 0.01147298 -0.01466576 -0.00783487 -0.02551963 -0.02508037
   -0.0115932  -0.02833921 -0.04328271 -0.04807395  0.02363879]
  [-0.02156421 -0.01743867  0.0058993  -0.03681654  0.02154856
    0.00935637 -0.01652386 -0.02215796  0.03750986 -0.03689753]
  [ 0.04422344 -0.02944503 -0.02354667  0.0357141  -0.04980476
   -0.03795732  0.00607185 -0.01719254 -0.01655592  0.01541667]
  [ 0.02022408 -0.01904036  0.00800767 -0.03566771  0.04453

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 275, 299, 177, 361])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]

In [1]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

voc_size = 1000
onehot_repr = [one_hot(words, voc_size) for words in sent]
onehot_repr

[[108, 274, 106, 998, 747, 809],
 [741, 238, 106, 803, 890, 696],
 [257, 405, 657, 3],
 [108, 973, 106, 588, 108, 320],
 [731, 560, 664, 106, 803, 890, 696],
 [133, 106, 803, 890, 433, 937]]

In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [5]:
sent_length = 20
padded_seq = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
padded_seq

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 108, 274, 106, 998, 747, 809],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 741, 238, 106, 803, 890, 696],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0, 257, 405, 657,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 108, 973, 106, 588, 108, 320],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        731, 560, 664, 106, 803, 890, 696],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 133, 106, 803, 890, 433, 937]])

In [6]:
model=Sequential()
model.add(Embedding(voc_size,15,input_length=sent_length))
model.compile('adam','mse')

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 15)            15000     
                                                                 
Total params: 15000 (58.59 KB)
Trainable params: 15000 (58.59 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
padded_seq[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 108, 274, 106, 998, 747, 809])

In [10]:
model.predict(padded_seq[0])

1/1 [==============================] - 0s 134ms/step


array([[ 0.03209949,  0.02205015, -0.00210519,  0.02513036, -0.03692713,
         0.00493582,  0.03697104,  0.0164313 , -0.01036721, -0.02372197,
         0.0018056 ,  0.02872724,  0.03148115,  0.01419928, -0.01488467],
       [ 0.03209949,  0.02205015, -0.00210519,  0.02513036, -0.03692713,
         0.00493582,  0.03697104,  0.0164313 , -0.01036721, -0.02372197,
         0.0018056 ,  0.02872724,  0.03148115,  0.01419928, -0.01488467],
       [ 0.03209949,  0.02205015, -0.00210519,  0.02513036, -0.03692713,
         0.00493582,  0.03697104,  0.0164313 , -0.01036721, -0.02372197,
         0.0018056 ,  0.02872724,  0.03148115,  0.01419928, -0.01488467],
       [ 0.03209949,  0.02205015, -0.00210519,  0.02513036, -0.03692713,
         0.00493582,  0.03697104,  0.0164313 , -0.01036721, -0.02372197,
         0.0018056 ,  0.02872724,  0.03148115,  0.01419928, -0.01488467],
       [ 0.03209949,  0.02205015, -0.00210519,  0.02513036, -0.03692713,
         0.00493582,  0.03697104,  0.0164313 , 

In [12]:
print(model.predict(padded_seq)[0])

1/1 [==============================] - 0s 39ms/step
[[ 0.03209949  0.02205015 -0.00210519  0.02513036 -0.03692713  0.00493582
   0.03697104  0.0164313  -0.01036721 -0.02372197  0.0018056   0.02872724
   0.03148115  0.01419928 -0.01488467]
 [ 0.03209949  0.02205015 -0.00210519  0.02513036 -0.03692713  0.00493582
   0.03697104  0.0164313  -0.01036721 -0.02372197  0.0018056   0.02872724
   0.03148115  0.01419928 -0.01488467]
 [ 0.03209949  0.02205015 -0.00210519  0.02513036 -0.03692713  0.00493582
   0.03697104  0.0164313  -0.01036721 -0.02372197  0.0018056   0.02872724
   0.03148115  0.01419928 -0.01488467]
 [ 0.03209949  0.02205015 -0.00210519  0.02513036 -0.03692713  0.00493582
   0.03697104  0.0164313  -0.01036721 -0.02372197  0.0018056   0.02872724
   0.03148115  0.01419928 -0.01488467]
 [ 0.03209949  0.02205015 -0.00210519  0.02513036 -0.03692713  0.00493582
   0.03697104  0.0164313  -0.01036721 -0.02372197  0.0018056   0.02872724
   0.03148115  0.01419928 -0.01488467]
 [ 0.03209949